AGENCY_ACRONYMS = {
  'New York Police Department':'NYPD',
  'Los Angeles Police Department': 'LAPD',
  "Sheriff's Department":'Sheriffs',
  'Sheriff Office':'Sheriffs',
  "Sheriff's Office":'Sheriffs',
  'Police Department':'PD',
  'Police Deptartment': 'PD', #typo
}

# gross hack
# but we need some way to link the sequential images with fatal encounters
# and the designer is unable to change the output filename format
IMAGE_ID_LOOKUP = {
  "Raymond Herisse":1,
  "Stanley LaVon Gibson":2,
  "Jeremy Powell":3,
  "Aaron Hunter":4,
  "Ahmede Jabbar Bradley":5,
  "Amos G. Smith":6,
  "Anthony Rawls":7,
  "Bobby Moore III":8,
  "Cameron Massey":9,
  "Carleton J. Wallace":10,
  "Carulus Hines":11,
  "Cheryl Blount-Burton":12,
  "Dakota Bright":13,
  "David Lee Turner":14,
  "Dawntree Ta'Shawn Williams":15,
  "DeJuan Colbert":16,
  "Demarcus Derell Celestine":17,
  "Deonte Traylor":18,
  "Herman Pickens":19,
  "Ishmael Muhammad":20,
  "Jack Lamar Robertson":21,
  "Jacqueline Culp":22,
  "Jalen Ricks":23,
  "James Brissette":24,
  "Joetavius Stafford":25,
  "Jonathan A. Ferrell":26,
  "Kenneth Chamberlain Sr.":27,
  "Kenneth Dewayne Cooper":28,
  "Kenneth Harding":29,
  "Kevin M. Bailey":30,
  "Kevin Willingham":31,
  "Kimani Gray":32,
  "Korey Marcel Germaine":33,
  "Latricka Sloan":34,
  "Mister Bobby Lowe":35,
  "Monroe Isadore":36,
  "Montellis Clark":37,
  "Ray Charles Hayes":38,
  "Raymond A. Smith":39,
  "Ron Pettaway":40,
  "Ronald Madison":41,
  'Sammie "Junebug" Davis Jr.':42,
  "Samuel Thomas Cunningham III":43,
  "Shelley Amos":44,
  "Taft Sellers":45,
  "Tendai Nhekairo":46,
  "Terry Laffitte":47,
  "Timothy Stansbury Jr.":48,
  "Tony Louis Francis":49,
  "Trevion Davis":50,
  "Waseem Jung":51,
  "Willie Davis Jr.":52,
  "Tyler Damon Woods":53,
  "Alan Blueford":54,
  "Anita Gay":55,
  "Booker Carloss II":56,
  "Darris Eugene Johnson":57,
  "Derrick Jones":58,
  "James Jahar Perez":59,
  "John Sloan":60,
  "Johnny Lee Wicks":61,
  "Keaton Dupree Otis":62,
  "Kendra James":63,
  "Lovelle Mixon":64,
  "Raheim Brown":65,
  "Tyrise M. Bell":66,
  "Willie Wilkens":67,
  "Oscar Grant III":68,
  "D'Andre Berghardt Jr.":69,
  "Alfred Redwine":70,
  "Vincent Wood":71,
  "James Lewis":72,
  "Thomas G. Manuel III":73,
  "Alexander Wilson":74,
  "Dennis Clark III":75,
  "Kenzell Hobbs":76,
  "Cary Ball":77,
  "James Coleman":78,
  "Cody Point":79,
  "Byron Carter Jr.":80,
  "Tavontae Jamar Haney":81,
  "Ryan Koontz":82,
  "Kenneth Knight":83,
  "Stephen O'Neal Wattley II":84,
  "Malik Williams":85,
  "Gabriel Winzer":86,
  "Thomas Dewitt Johnson":87,
  "Eddie Callaway":88,
  "Carnell Moore":89,
  "Jordan West-Morson":90,
  "Marquis Spencer":91,
  "Tywon Jones":92,
  "Emmanuel Gatewood":93,
  "Kourtney Hahn":94,
  "Kendra Diggs":95,
  "Shaaliver Douse":96,
  "Maurice Leroy Cox":97,
  "Darrien Hunt":98,
  "Howard Wallace Bowe Jr.":99,
  "Anton Barrett":100,
  "Mario Romero":101,
  "Kendrec McDade":102,
  "Terrance Terrell Franklin":103,
  'Gerald "Skip" Tyrone Murphy':104,
  "Louis M. Squires":105,
  "Frankie Pitt":106,
  "Ramarley Graham":107,
  "Lejoy Grissom":108,
  "Terrence Dawson":109,
  "Henry Glover":110,
  'Joshua "Omar" Johnson':111,
  "Anthony Michael Bland":112,
  "Clinton Roebexar Allen":113,
  "Julian Dawkins":114,
  "Thomas Bean":115,
  "Ajani Mitchell":116,
  "William Dupree":117,
  "Jaleel Jackson":118,
  "Nathaniel McRae":119,
  "Gary Hatcher":120,
  "Aiyana Mo'Nay Stanley Jones":121,
  "Jermie McCraven":122,
  "Christian Freeman":123,
  "Lorenzo Davis":124,
  "Justin Thompson":125,
  "Charles Livingston III":126,
  "Steven Askew":127,
  "Horace Whiting":128,
  "Marvin Amerson":129,
  "Aaron Dumas":130,
  "Dwight Moorer Jr.":131,
  "Edward Mwaura":132,
  "Sherlon Smikle":133,
  "Lana Morris":134,
  "Joseph Paige":135,
  "Darrius J. Lowery-Baptiste":136,
  "Wayne Arnold Jones":137,
  "Joe White III":138,
  "Recardio Shormon Clark":139,
  "Sammie Lamont Wallace":140,
  "Michael Westly":141,
  "Cedric Howard":142,
  "Eliakim Shabazz":143,
  "Jaquaz Walker":144,
  "Lawrence Allen":145,
  "Adolphus Pinkney":146,
  "Donnell Carter":147,
  "Jourdan Akili Wagner":148,
  "Cacedrick White":149,
  "Elip Cheatham":150,
  "Michael Lembhard":151,
  "Terry Davis":152,
  "Deangelo Lopez":153,
  "James Eric Griffin":154,
  "Willie Sudduth":155,
  "Kenneth Smith":156,
  "Aron Jones":157,
  "Brandon McCloud":158,
  "Icarus Randolph":159,
  "Eric Gardner":160,
  "Miriam Iris Carey":161,
  "Larry Eugene Jackson Jr.":162,
  "Dontre Hamilton":163,
  "Bryan Stukes":164,
  "Steven Tyrone Mallory":165,
  "Ezell Ford":166,
  "Micah Anthony Key":167,
  "Seneca Darden":168,
  "David Latham":169,
  "Darius Colegarrit":170,
  "Warren Robinson":171,
  "Rekia Boyd":172,
  "Flint Farmer":173,
  "Burrell Ramsey-White":174,
  "Travis Floyd":175,
  "Dartanya Bentley, Jr.":176,
  "Timothy Thomas":177,
  "Remis M. Andrews":178,
  "John H. Crawford III":179,
  "Derek Deandre Walker":180,
  "Hydra Lacy Jr.":181,
  "Michelle Cusseaux":182,
  "Milton Hall":183,
  "Stephon Watts":184,
  "Davon Mullins":185,
  "Danroy Henry Jr.":186,
  "Greg Thompson Jr.":187,
  "Idriss Shelley":188,
  "Howard Tucker":189,
  "Nahcream Moore":190,
  "Jerry Brown":191,
  "Londrell E. Johnson":192,
  "Jason Harrison":193,
  "Brian Simms Jr.":194,
  "Yvette Smith":195,
  "Kayla Moore":196,
  "Oliver 'Big 'O'' Lefiti":197,
  "Kathryn Johnston":198,
  "Antonio Latuanee Pryce":199,
  "Albert Duane Denton":200,
  "Victor White III":201,
  "Donte Lamonte Jordan":202,
  "Jose Valerio":203,
  "Rexford Dasrath":204,
  "Michael Moore":205,
  "Ismael Sadiq":206,
  "Eurie Stamps":207,
  "Eddie Davis":208,
  "Kajieme Powell":209,
  "Sean Greenwood":210,
  "Mark Salazar":211,
  'Clifton "Pete" Lee Jr.':212,
  "Jacorey Calhoun":213,
  "Nathaniel McRae":214,
  "Maurice Clemmons":215,
  "John Franklin Brown":216,
  "Bert W. Bowen":217,
  "Justin Sipp":218,
  "Hailu Brook":219,
  "Wendell Allen":220,
  "Michael McCullen":221,
  "Tarika Wilson":222,
  "John Bior Deng":223,
  "Tommy Yancy":224,
  "La-Reko Williams":225,
  "Roshad McIntosh":226,
  "Desean Pittman":227,
  "Rondre Hornbeak":228,
  "Dante Parker":229,
  "Jacorey Calhoun":230,
  "Steven Lashone Douglas":231,
  "Sean Bell":232,
  "Chavis Carter":233,
  "Victor Demarius Steen":234,
  "Manuel Loggins Jr.":235,
  "Melvin Lawhorn":236,
  "Jordan Baker":237,
  "Timothy Russell":238,
  "Steve Eugene Washington":239,
  "Ousmane Zongo":240,
  "Albert Rucker":241,
  "Cortez Washington":242,
  "Montez Dewayne Hambric":243,
  "Tyrone Brown":244,
  "Malissa Williams":245,
  "James Rivera":246,
  "Julian Alexander":247,
  "Woodrow Player III":248,
  "Alberta Spruill":249,
  "Ernest Vassell":250,
  "Kiwane Carrington":251,
  "Marquise Jones":252,
  "Michael Blair":253,
  "Justin Fields":254,
  "Larry Jerome Jenkins":255,
  "Eugene N. Turner III":256,
  "Mark Fernandes McMullen":257,
  "Guy Jermone Jarreau Jr.":258,
  "Russell Lydell Smith":259,
  "James Lamont":260,
  "Desjon Jamal Edwards":261,
  "Donovan Tyrone Graham":262,
  "Jashon Bryant":263,
  "Marcus G. Brown":264,
  "Othniel Askew":265,
  "Lavon King":266,
  "Aaron Harrison":267,
  "Ryan L. Stokes":268,
  "Gregory Lewis Towns Jr":269,
  "Malcolm Ferguson":270,
  "Marlon Horton":271,
  "Manuel DaVeiga":272,
  "Tahiem Goffe":273,
  "Joseph Ramos":274,
  "Kerby Revelus":275,
  "Denis Reynoso":276,
  "Brandon Payne":277,
  "Delano M. Walker":278,
}